const fixCss=document.createElement('link');fixCss.rel='stylesheet';fixCss.href='/invest/v2-fixes.css?v=4';document.head.appendChild(fixCss);
const SEARCH_API='https://zbtijblvkzkeposvkfob.supabase.co/functions/v1/invest-public-search';
const MARKET_API='https://zbtijblvkzkeposvkfob.supabase.co/functions/v1/invest-market-strip';
const MACRO_API='https://zbtijblvkzkeposvkfob.supabase.co/functions/v1/invest-macro-market';
const fallbackMarket=[
{label:'Itaú PN',price:42.39,day_change_pct:.0009445100},{label:'B3 ON',price:17.35,day_change_pct:-.0011514105},{label:'WEG ON',price:51.02,day_change_pct:.0055183287},{label:'Ambev ON',price:15.73,day_change_pct:-.0088216761},{label:'Localiza ON',price:35.78,day_change_pct:.0053385783},{label:'Lojas Renner ON',price:11.20,day_change_pct:-.0008920607},{label:'PRIO ON',price:64.24,day_change_pct:.0051635112},{label:'Porto ON',price:49.81,day_change_pct:-.0045963229},{label:'Vivara ON',price:22.43,day_change_pct:.0013392857},{label:'Raia Drogasil ON',price:19.57,day_change_pct:.0015353122},{label:'BTG Pactual Units',price:60.22,day_change_pct:-.0042989418},{label:'CPFL Energia ON',price:44.91,day_change_pct:.0040241449}
];
const fmtMoney=v=>v==null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmtNum=(v,d=2)=>v==null?'—':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const fmtPct=v=>v==null?'—':(Number(v)*100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
async function fetchJSON(url,tries=4){let last;for(let i=0;i<tries;i++){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),15000);try{const sep=url.includes('?')?'&':'?';const r=await fetch(url+sep+'_='+Date.now(),{cache:'no-store',mode:'cors',signal:ctrl.signal,headers:{Accept:'application/json'}});clearTimeout(timer);if(!r.ok){const body=await r.text().catch(()=> '');throw new Error('HTTP '+r.status+' '+body.slice(0,180));}const j=await r.json();if(j?.error)throw new Error(j.error);return j;}catch(e){clearTimeout(timer);last=e;if(i<tries-1)await new Promise(res=>setTimeout(res,800*(i+1)));}}throw last;}
function marketItem(r){const ch=Number(r.day_change_pct);const cls=!Number.isFinite(ch)||ch===0?'flat':ch>0?'up':'down';const arrow=!Number.isFinite(ch)||ch===0?'':ch>0?'▲':'▼';return `<div class="market-item"><span class="market-label">${esc(r.label||r.ticker)}</span><span class="market-price">${fmtMoney(r.price)}</span><span class="market-change ${cls}">${arrow}${arrow?' ':''}${fmtPct(Number.isFinite(ch)?ch:null)}</span></div>`;}
function renderMarket(data){const base=Array.isArray(data)&&data.length?data:fallbackMarket;const expanded=[...base,...base];const html=expanded.map(marketItem).join('');document.getElementById('tickerA').innerHTML=html;document.getElementById('tickerB').innerHTML=html;}
async function loadMarket(){try{const j=await fetchJSON(MARKET_API,4);renderMarket(j.data);}catch(e){console.error('AXIVA market error',e);renderMarket(fallbackMarket);}}
function val(id){return document.getElementById(id).value.trim().replace(',','.');}
async function buscar(){const panel=document.getElementById('filterPanel');const out=document.getElementById('results');panel.classList.add('loading');out.innerHTML='<div class="empty">Analisando empresas...</div>';const q=new URLSearchParams({limit:'25'});const ticker=document.getElementById('ticker').value.trim();if(ticker)q.set('ticker',ticker);[['plMax','pl_max'],['roeMin','roe_min'],['roicMin','roic_min'],['dyMin','dy_min']].forEach(([id,key])=>{const v=val(id);if(v!=='')q.set(key,v);});try{const j=await fetchJSON(SEARCH_API+'?'+q.toString(),4);renderResults(Array.isArray(j.data)?j.data:[]);}catch(e){console.error('AXIVA search error',e);out.innerHTML='<div class="empty"><b>A consulta não pôde ser concluída.</b><br>Atualize a página e tente novamente.</div>';}finally{panel.classList.remove('loading');}}
function renderResults(rows){const out=document.getElementById('results');if(!rows.length){out.innerHTML='<div class="empty">Nenhuma empresa encontrada com esses critérios.</div>';return;}out.innerHTML=rows.map(r=>{const ch=Number(r.day_change_pct);const cls=!Number.isFinite(ch)||ch===0?'flat':ch>0?'up':'down';const arrow=!Number.isFinite(ch)||ch===0?'':ch>0?'▲':'▼';return `<article class="result-card"><div class="result-top"><div class="company-block"><strong>${esc(r.ticker)}</strong><span>${esc(r.company_name||'')}</span></div><div class="quote-block"><strong>${fmtMoney(r.current_price)}</strong><span class="quote-change ${cls}">${arrow}${arrow?' ':''}${fmtPct(Number.isFinite(ch)?ch:null)}</span></div></div><div class="fundamentals"><div class="fundamental"><span>P/L</span><b>${fmtNum(r.pl)}</b></div><div class="fundamental"><span>P/VP</span><b>${fmtNum(r.pvp)}</b></div><div class="fundamental"><span>DY</span><b>${fmtPct(r.dividend_yield)}</b></div><div class="fundamental"><span>ROE</span><b>${fmtPct(r.roe)}</b></div><div class="fundamental"><span>ROIC</span><b>${fmtPct(r.roic)}</b></div></div><div class="premium-row"><div class="premium-box"><span>Preço-alvo</span><b>R$ 00,00</b></div><div class="premium-box"><span>Graham</span><b>R$ 00,00</b></div><div class="premium-cta">Tenha acesso na área exclusiva para assinantes</div></div></article>`;}).join('');}
function setupHeroMacro(){const panel=document.querySelector('.hero-panel');if(!panel)return;panel.classList.add('macro-panel');panel.innerHTML=`<div class="panel-head"><strong>Mercado hoje</strong><span class="tag">AXIVA Invest</span></div><div class="macro-grid"><div class="macro-card" data-macro="BRL=X"><span class="macro-label">Dólar comercial</span><strong class="macro-value">—</strong><span class="macro-change flat">—</span></div><div class="macro-card" data-macro="EURBRL=X"><span class="macro-label">Euro</span><strong class="macro-value">—</strong><span class="macro-change flat">—</span></div><div class="macro-card" data-macro="^BVSP"><span class="macro-label">Ibovespa</span><strong class="macro-value">—</strong><span class="macro-change flat">—</span></div><div class="macro-card" data-macro="CDI"><span class="macro-label">CDI</span><strong class="macro-value">—</strong><span class="macro-change flat">—</span></div></div><div class="macro-foot">Atualização automática</div>`;}
function macroValue(item){const v=Number(item.value);if(!Number.isFinite(v))return '—';if(item.unit==='BRL')return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2});if(item.unit==='PTS')return v.toLocaleString('pt-BR',{maximumFractionDigits:0})+' pts';if(item.unit==='% a.d.')return v.toLocaleString('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:4})+'% a.d.';return fmtNum(v);}
function renderMacro(data){(Array.isArray(data)?data:[]).forEach(item=>{const key=String(item.key||'');const card=[...document.querySelectorAll('[data-macro]')].find(el=>el.getAttribute('data-macro')===key);if(!card)return;const value=card.querySelector('.macro-value');const change=card.querySelector('.macro-change');value.textContent=macroValue(item);const ch=Number(item.change_pct);const finite=Number.isFinite(ch);const cls=!finite||ch===0?'flat':ch>0?'up':'down';const arrow=!finite||ch===0?'':ch>0?'▲':'▼';change.className='macro-change '+cls;change.textContent=!finite?'—':`${arrow}${arrow?' ':''}${fmtPct(ch)}`;});}
async function loadMacro(){try{const j=await fetchJSON(MACRO_API,3);if(Array.isArray(j.data)){renderMacro(j.data);try{localStorage.setItem('axiva_macro_cache',JSON.stringify(j.data));}catch(_){ }return;}throw new Error('macro_data_invalid');}catch(e){console.error('AXIVA macro error',e);try{const cached=JSON.parse(localStorage.getItem('axiva_macro_cache')||'[]');if(Array.isArray(cached)&&cached.length)renderMacro(cached);}catch(_){ }}}
function applyTextFixes(){const h2=document.querySelector('#metodologia .section-head h2');if(h2)h2.textContent='Você não precisa analisar centenas de empresas.';}
window.addEventListener('DOMContentLoaded',()=>{setupHeroMacro();applyTextFixes();document.getElementById('searchBtn')?.addEventListener('click',buscar);document.querySelectorAll('.filters input').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter')buscar();}));renderMarket(fallbackMarket);loadMarket();loadMacro();setInterval(loadMarket,120000);setInterval(loadMacro,120000);});