import React from 'react';
import { useState } from 'react';
import { MockupBadge, MockupStat, MiniLineChart, MiniBarChart, QualityIndicator } from '../shared/MockupElements.js';
const tabs = ['Valor', 'Qualidade', 'Fundamentos', 'Histórico', 'Comparação'];
export default function PriceIsPart() {
    const [active, setActive] = useState('Valor');
    return (React.createElement("section", { id: "preco", className: "bg-axiva-navy py-16 lg:py-28" },
        React.createElement("div", { className: "mx-auto max-w-container px-4 lg:px-8" },
            React.createElement("div", { className: "mb-12 max-w-2xl" },
                React.createElement("div", { className: "flex items-center gap-2" },
                    React.createElement("span", { className: "h-px w-6 bg-axiva-green" }),
                    React.createElement("span", { className: "text-xs font-medium uppercase tracking-wider text-axiva-green" }, "Múltiplas dimensões")),
                React.createElement("h2", { className: "mt-3 text-2xl font-semibold text-white sm:text-3xl" }, "Preço é apenas uma parte da análise."),
                React.createElement("p", { className: "mt-4 text-base text-slate-300" }, "Entenda diferentes dimensões da empresa antes de formar sua própria conclusão.")),
            React.createElement("div", { className: "grid gap-6 lg:grid-cols-[220px_1fr] lg:gap-8" },
                React.createElement("nav", { className: "flex flex-row gap-1 overflow-x-auto hide-scrollbar lg:flex-col lg:gap-1", "aria-label": "Dimensões de análise" }, tabs.map((tab) => (React.createElement("button", { key: tab, onClick: () => setActive(tab), className: `shrink-0 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${active === tab
                        ? 'bg-axiva-green text-white'
                        : 'text-slate-400 hover:bg-axiva-navy-light hover:text-white'}`, "aria-current": active === tab }, tab)))),
                React.createElement("div", { className: "rounded-xl border border-slate-700 bg-axiva-navy-light p-5 sm:p-6" },
                    React.createElement("div", { className: "mb-4 flex items-center gap-2" },
                        React.createElement("span", { className: "text-sm font-semibold text-white" }, "PETR4"),
                        React.createElement("span", { className: "text-xs text-slate-400" }, "Petrobras PN"),
                        React.createElement(MockupBadge, { className: "border-slate-600 bg-slate-700/50 text-slate-400" }, "MOCKUP")),
                    active === 'Valor' && (React.createElement("div", { className: "animate-fade-in grid gap-5 sm:grid-cols-2 lg:grid-cols-4" },
                        React.createElement(MockupStat, { label: "Preço atual", value: "R$ 38,45", dark: true }),
                        React.createElement(MockupStat, { label: "Valor estimado", value: "R$ 42,10", dark: true }),
                        React.createElement(MockupStat, { label: "Desconto", value: "-8,7%", hint: "sobre valor estimado", dark: true }),
                        React.createElement(MockupStat, { label: "Graham", value: "R$ 45,20", dark: true }),
                        React.createElement("div", { className: "sm:col-span-2 lg:col-span-4" },
                            React.createElement("div", { className: "mb-2 text-[11px] font-medium text-slate-400" }, "Preço vs. Valor estimado"),
                            React.createElement(MiniLineChart, { className: "h-20 w-full" })))),
                    active === 'Qualidade' && (React.createElement("div", { className: "animate-fade-in flex flex-col gap-5" },
                        React.createElement("div", { className: "flex items-center justify-between" },
                            React.createElement("span", { className: "text-sm text-slate-300" }, "Indicador de qualidade"),
                            React.createElement(QualityIndicator, { score: 4 })),
                        React.createElement("div", { className: "grid gap-3 sm:grid-cols-2" }, [
                            { label: 'Lucro consistente', status: 'Sim' },
                            { label: 'ROE acima da média', status: 'Sim' },
                            { label: 'Baixo endividamento', status: 'Sim' },
                            { label: 'Crescimento de receita', status: 'Parcial' },
                        ].map((item) => (React.createElement("div", { key: item.label, className: "flex items-center justify-between rounded-lg border border-slate-700 px-3 py-2.5" },
                            React.createElement("span", { className: "text-xs text-slate-300" }, item.label),
                            React.createElement("span", { className: `text-xs font-medium ${item.status === 'Sim' ? 'text-axiva-green-light' : 'text-yellow-400'}` }, item.status))))))),
                    active === 'Fundamentos' && (React.createElement("div", { className: "animate-fade-in grid gap-3 sm:grid-cols-3 lg:grid-cols-6" }, [
                        { label: 'P/L', value: '5,8' },
                        { label: 'P/VP', value: '1,2' },
                        { label: 'ROE', value: '28,4%' },
                        { label: 'ROIC', value: '19,2%' },
                        { label: 'DY', value: '14,2%' },
                        { label: 'Margem líq.', value: '24,8%' },
                    ].map((stat) => (React.createElement("div", { key: stat.label, className: "rounded-lg border border-slate-700 px-3 py-3" },
                        React.createElement("div", { className: "text-[10px] font-medium uppercase tracking-wide text-slate-500" }, stat.label),
                        React.createElement("div", { className: "mt-1 text-sm font-semibold text-white" }, stat.value)))))),
                    active === 'Histórico' && (React.createElement("div", { className: "animate-fade-in flex flex-col gap-5" },
                        React.createElement("div", null,
                            React.createElement("div", { className: "mb-2 text-[11px] font-medium text-slate-400" }, "Evolução do P/L, 5 anos"),
                            React.createElement(MiniBarChart, { values: [8, 7, 6, 7, 5], className: "h-20" })),
                        React.createElement("div", null,
                            React.createElement("div", { className: "mb-2 text-[11px] font-medium text-slate-400" }, "Evolução do ROE, 5 anos"),
                            React.createElement(MiniBarChart, { values: [22, 25, 27, 26, 28], className: "h-20" })))),
                    active === 'Comparação' && (React.createElement("div", { className: "animate-fade-in overflow-x-auto" },
                        React.createElement("table", { className: "w-full text-sm" },
                            React.createElement("thead", null,
                                React.createElement("tr", { className: "border-b border-slate-700" },
                                    React.createElement("th", { className: "pb-2 pr-4 text-left text-[11px] font-medium uppercase tracking-wide text-slate-400" }, "Indicador"),
                                    React.createElement("th", { className: "pb-2 px-4 text-left text-[11px] font-medium uppercase tracking-wide text-slate-400" }, "PETR4"),
                                    React.createElement("th", { className: "pb-2 px-4 text-left text-[11px] font-medium uppercase tracking-wide text-slate-400" }, "ITUB4"),
                                    React.createElement("th", { className: "pb-2 px-4 text-left text-[11px] font-medium uppercase tracking-wide text-slate-400" }, "VALE3"))),
                            React.createElement("tbody", null, [
                                { label: 'Preço', a: 'R$ 38,45', b: 'R$ 33,20', c: 'R$ 61,30' },
                                { label: 'Valor estimado', a: 'R$ 42,10', b: 'R$ 36,80', c: 'R$ 58,00' },
                                { label: 'P/L', a: '5,8', b: '8,2', c: '6,1' },
                                { label: 'ROE', a: '28,4%', b: '22,1%', c: '19,8%' },
                                { label: 'DY', a: '14,2%', b: '6,8%', c: '8,5%' },
                            ].map((row) => (React.createElement("tr", { key: row.label, className: "border-b border-slate-700/50" },
                                React.createElement("td", { className: "py-2.5 pr-4 text-xs text-slate-400" }, row.label),
                                React.createElement("td", { className: "py-2.5 px-4 text-sm font-medium text-white" }, row.a),
                                React.createElement("td", { className: "py-2.5 px-4 text-sm font-medium text-white" }, row.b),
                                React.createElement("td", { className: "py-2.5 px-4 text-sm font-medium text-white" }, row.c)))))))))))));
}
