import React from 'react';
import { useState } from 'react';
import { formatCurrency, formatNumber, formatPercent, formatSignedPercent } from '/invest/app/data/investData.js';
import { MiniBarChart, MiniLineChart, MockupStat, QualityIndicator } from '/invest/app/components/shared/MockupElements.js';
const tabs = ['Visão geral', 'Fundamentos', 'Valuation', 'Histórico'];
export default function CompanyPreview({ company, compact = false }) {
    const [active, setActive] = useState('Visão geral');
    return (React.createElement("div", { className: `p-5 sm:p-6 ${compact ? '' : ''}` },
        React.createElement("div", { className: "mb-5 flex items-start justify-between gap-4" },
            React.createElement("div", null,
                React.createElement("div", { className: "flex items-center gap-2" },
                    React.createElement("span", { className: "text-lg font-bold text-axiva-navy" }, company.ticker)),
                React.createElement("span", { className: "text-xs text-slate-400" }, company.name)),
            React.createElement(QualityIndicator, { score: company.quality })),
        React.createElement("div", { className: "mb-5 grid grid-cols-2 gap-4 sm:grid-cols-4" },
            React.createElement(MockupStat, { label: "Preço atual", value: formatCurrency(company.price) }),
            React.createElement(MockupStat, { label: "Valor estimado", value: formatCurrency(company.estimated) }),
            React.createElement(MockupStat, { label: company.discount <= 0 ? 'Desconto' : 'Ágio', value: formatSignedPercent(company.discount), hint: "vs. valor estimado" }),
            React.createElement(MockupStat, { label: "Graham", value: formatCurrency(company.graham) })),
        React.createElement("div", { className: "mb-5 rounded-lg border border-slate-200 p-3" },
            React.createElement("div", { className: "mb-2 flex items-center justify-between" },
                React.createElement("span", { className: "text-[11px] font-medium text-slate-400" }, "Histórico de preço, 6 meses"),
                React.createElement("span", { className: `text-[11px] font-medium ${company.performance6m && company.performance6m >= 0 ? 'text-axiva-green' : 'text-red-500'}` }, company.performance6m ? formatSignedPercent(company.performance6m) : 'N/D')),
            React.createElement(MiniLineChart, { values: company.history6m, className: `${compact ? 'h-16' : 'h-20'} w-full` })),
        active === 'Visão geral' && (React.createElement("div", { className: "animate-fade-in grid grid-cols-3 gap-3 sm:grid-cols-6" }, [
            { label: 'P/L', value: formatNumber(company.pl, 2) },
            { label: 'P/VP', value: formatNumber(company.pvp, 2) },
            { label: 'ROE', value: formatPercent(company.roe) },
            { label: 'ROIC', value: company.roic == null ? 'N/D' : formatPercent(company.roic) },
            { label: 'DY', value: formatPercent(company.dy) },
            { label: 'Qualidade', value: `${company.quality}/5` },
        ].map((stat) => (React.createElement("div", { key: stat.label, className: "rounded-lg border border-slate-100 bg-slate-50 px-2.5 py-2" },
            React.createElement("div", { className: "text-[10px] font-medium uppercase tracking-wide text-slate-400" }, stat.label),
            React.createElement("div", { className: "mt-0.5 text-sm font-semibold text-axiva-navy" }, stat.value)))))),
        active === 'Fundamentos' && (React.createElement("div", { className: "animate-fade-in grid grid-cols-2 gap-3 sm:grid-cols-3" }, [
            { label: 'Setor', value: company.sector },
            { label: 'Subsetor', value: company.subsector ?? 'N/D' },
            { label: 'LPA', value: company.lpa == null ? 'N/D' : formatNumber(company.lpa, 2) },
            { label: 'VPA', value: company.vpa == null ? 'N/D' : formatNumber(company.vpa, 2) },
            { label: 'Margem líquida', value: company.margin == null ? 'N/D' : formatPercent(company.margin) },
            { label: 'Crescimento 5a', value: company.growth5y == null ? 'N/D' : formatSignedPercent(company.growth5y) },
        ].map((stat) => (React.createElement("div", { key: stat.label, className: "rounded-lg border border-slate-100 bg-slate-50 px-3 py-3" },
            React.createElement("div", { className: "text-[10px] font-medium uppercase tracking-wide text-slate-400" }, stat.label),
            React.createElement("div", { className: "mt-1 text-sm font-semibold text-axiva-navy" }, stat.value)))))),
        active === 'Valuation' && (React.createElement("div", { className: "animate-fade-in grid gap-3 sm:grid-cols-2" },
            React.createElement("div", { className: "rounded-lg border border-slate-200 p-4" },
                React.createElement("div", { className: "mb-2 text-[11px] font-medium uppercase tracking-wide text-slate-400" }, "Comparação de preço"),
                React.createElement("div", { className: "flex items-end justify-between gap-4" },
                    React.createElement("div", null,
                        React.createElement("div", { className: "text-xs text-slate-400" }, "Preço atual"),
                        React.createElement("div", { className: "text-lg font-semibold text-axiva-navy" }, formatCurrency(company.price))),
                    React.createElement("div", null,
                        React.createElement("div", { className: "text-xs text-slate-400" }, "Valor estimado"),
                        React.createElement("div", { className: "text-lg font-semibold text-axiva-navy" }, formatCurrency(company.estimated))),
                    React.createElement("div", null,
                        React.createElement("div", { className: "text-xs text-slate-400" }, "Graham"),
                        React.createElement("div", { className: "text-lg font-semibold text-axiva-navy" }, formatCurrency(company.graham))))),
            React.createElement("div", { className: "rounded-lg border border-slate-200 p-4" },
                React.createElement("div", { className: "mb-2 text-[11px] font-medium uppercase tracking-wide text-slate-400" }, "Leitura rápida"),
                React.createElement("div", { className: "space-y-2" }, company.notes?.map((note) => (React.createElement("div", { key: note, className: "flex items-start gap-2 text-sm text-axiva-gray" },
                    React.createElement("span", { className: "mt-1 h-1.5 w-1.5 rounded-full bg-axiva-green" }),
                    React.createElement("span", null, note)))))))),
        active === 'Histórico' && (React.createElement("div", { className: "animate-fade-in flex flex-col gap-5" },
            React.createElement("div", null,
                React.createElement("div", { className: "mb-2 text-[11px] font-medium text-slate-400" }, "Evolução do P/L, 5 anos"),
                React.createElement(MiniBarChart, { values: company.plHistory5y ?? [], className: "h-20" })),
            React.createElement("div", null,
                React.createElement("div", { className: "mb-2 text-[11px] font-medium text-slate-400" }, "Evolução do ROE, 5 anos"),
                React.createElement(MiniBarChart, { values: company.roeHistory5y ?? [], className: "h-20" })))),
        React.createElement("div", { className: "mt-5 flex gap-2 border-b border-slate-200 pb-0" }, tabs.map((tab) => (React.createElement("button", { key: tab, onClick: () => setActive(tab), className: `rounded-t-lg px-3 py-2 text-xs font-medium transition-colors ${active === tab ? 'border-b-2 border-axiva-green text-axiva-navy' : 'text-slate-400 hover:text-axiva-gray'}` }, tab))))));
}
